### ISSUE TITLE
gyp ERR

### ISSUE THREAD

**Issue by wojiaoerdandan** [sthnaqvi/explorer#13]
13 warnings and 1 error generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/guoyaping/Desktop/explorer-master/node_modules/_bufferutil@1.3.0@bufferutil
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
⠙ [6/13] Installing yallist@^2.1.2[npminstall:runscript:error] crypto-socket@1.2.0 › bufferutil@^1.2.1 has binding.gyp file, run "node-gyp rebuild" error: RunScriptError: Run "sh -c node-gyp rebuild" error, exit code 1
5 warnings and 1 error generated.

**Comment by Paullaw102** [comment]
nvm install v8.11.3  #  download node
nvm alias default 8.11.3 #set 8.11.3 to the default version
