### ISSUE TITLE
Web3 is not a constructor and nothing showing up

### ISSUE THREAD

**Issue by Alaradia** [sthnaqvi/explorer#4]
`jquery.min.js:2 jQuery.Deferred exception: Web3 is not a constructor TypeError: Web3 is not a constructor
    at http://yoscan.io/app.js:83:20
    at Object.e [as invoke] (http://yoscan.io/bower_components/angular/angular.min.js:40:19)
    at http://yoscan.io/bower_components/angular/angular.min.js:41:390
    at p (http://yoscan.io/bower_components/angular/angular.min.js:7:355)
    at db (http://yoscan.io/bower_components/angular/angular.min.js:41:366)
    at c (http://yoscan.io/bower_components/angular/angular.min.js:19:463)
    at yc (http://yoscan.io/bower_components/angular/angular.min.js:20:274)
    at de (http://yoscan.io/bower_components/angular/angular.min.js:19:83)
    at HTMLDocument.<anonymous> (http://yoscan.io/bower_components/angular/angular.min.js:299:474)
    at j (http://yoscan.io/bower_components/jquery/dist/jquery.min.js:2:29999) undefined
r.Deferred.exceptionHook @ jquery.min.js:2
jquery.min.js:2 Uncaught TypeError: Web3 is not a constructor
    at app.js:83
    at Object.e [as invoke] (angular.min.js:40)
    at angular.min.js:41
    at p (angular.min.js:7)
    at db (angular.min.js:41)
    at c (angular.min.js:19)
    at yc (angular.min.js:20)
    at de (angular.min.js:19)
    at HTMLDocument.<anonymous> (angular.min.js:299)
    at j (jquery.min.js:2)`

**Comment by Alaradia** [comment]
Fixed just had to bower install --force just previous packages from carsenks messing with it
